/**
 * Bridge scaffolding — emits a working starter for a new bridge.
 *
 * From FLAIR-BRIDGES.md §2: "Scaffold & test in-tree. `flair bridge
 * scaffold <name>` emits a working starter; `flair bridge test <name>`
 * runs a round-trip diff." This file handles the `scaffold` half.
 *
 * Two shapes supported:
 *  - --file: YAML descriptor at `.flair-bridge/<name>.yaml` + fixture
 *  - --api:  TS code plugin at `flair-bridge-<name>/` + package.json + fixture
 */

import { promises as fsp } from "node:fs";
import { join, dirname } from "node:path";
import type { BridgeKind } from "./types.js";

export interface ScaffoldOptions {
  name: string;
  kind: BridgeKind;
  cwd?: string;
  /** Overwrite existing files instead of erroring. */
  force?: boolean;
}

export interface ScaffoldResult {
  createdFiles: string[];
  skippedFiles: string[];
  summary: string;
}

const NAME_RE = /^[a-z][a-z0-9-]*[a-z0-9]$/;

async function exists(path: string): Promise<boolean> {
  try { await fsp.stat(path); return true; } catch { return false; }
}

async function writeIfAbsent(
  path: string,
  content: string,
  force: boolean,
): Promise<{ wrote: boolean }> {
  if (!force && (await exists(path))) return { wrote: false };
  await fsp.mkdir(dirname(path), { recursive: true });
  await fsp.writeFile(path, content, "utf-8");
  return { wrote: true };
}

function fileDescriptorTemplate(name: string): string {
  return `# .flair-bridge/${name}.yaml
#
# Generated by \`flair bridge scaffold ${name} --file\`.
# Edit to match your foreign system, then run \`flair bridge test ${name}\`.
#
# Spec: see FLAIR-BRIDGES.md §4 (memory schema) and §5 (YAML shape).
name: ${name}
version: 1
kind: file
# description shown in 'flair bridge list':
description: "TODO — one-line description of what this bridge does"

# 'detect' lets auto-discovery confirm the foreign system is present.
# Use 'anyExists' (any one path matching is enough) or 'allExist'.
detect:
  anyExists:
    - ".example/AGENTS.md"

# Import: foreign → Flair memories.
import:
  sources:
    - path: ".example/memory/lessons.jsonl"
      format: jsonl          # jsonl | json | yaml | markdown-frontmatter
      map:
        # JSONPath subset: $.field, $.nested.field, $.array[*]
        content: "$.claim"
        subject: "$.topic"
        tags: "$.tags"
        foreignId: "$.id"
        durability: "persistent"
        source: "${name}/lessons"

# Export: Flair memories → foreign. Optional. Drop this block if read-only.
export:
  targets:
    - path: ".example/memory/lessons.jsonl"
      format: jsonl
      # 'when' is a boolean expression over BridgeMemory fields.
      # Omit for "always export".
      when: "durability in ['persistent', 'permanent']"
      map:
        # Right-hand side is a BridgeMemory field (or expression).
        id: "foreignId ?? id"
        claim: "content"
        topic: "subject"
        tags: "tags"
`;
}

function fileFixtureTemplate(name: string): string {
  // JSONL fixture matching the default template's 'sources[0].path'.
  return [
    JSON.stringify({ id: "lesson-1", claim: "Always run tests before pushing.", topic: "engineering", tags: ["process", "ci"] }),
    JSON.stringify({ id: "lesson-2", claim: "Name workarounds as workarounds.", topic: "communication", tags: ["writing"] }),
    "",
  ].join("\n");
}

function apiIndexTemplate(name: string): string {
  return `/**
 * flair-bridge-${name}
 *
 * Generated by \`flair bridge scaffold ${name} --api\`.
 * Spec: see FLAIR-BRIDGES.md §4 (memory schema) and §6 (code plugin shape).
 *
 * After editing, run:
 *   flair bridge test ${name}
 */

import type {
  MemoryBridge,
  BridgeMemory,
  BridgeContext,
} from "@tpsdev-ai/flair";

export const bridge: MemoryBridge = {
  name: "${name}",
  version: 1,
  kind: "api",

  options: {
    apiKey:  { env: "${name.toUpperCase().replace(/-/g, "_")}_API_KEY", required: true, description: "API token" },
    userId:  { required: true, description: "Account or user identifier in the foreign system" },
    baseUrl: { default: "https://api.example.com", description: "Foreign API base URL" },
  },

  async *import(opts, ctx: BridgeContext): AsyncIterable<BridgeMemory> {
    ctx.log.info("starting import", { user: String(opts.userId) });
    const res = await ctx.fetch(\`\${String(opts.baseUrl)}/v1/memories?user=\${String(opts.userId)}\`, {
      headers: { Authorization: \`Bearer \${String(opts.apiKey)}\` },
    });
    if (!res.ok) {
      throw new Error(\`foreign API returned \${res.status}: \${await res.text()}\`);
    }
    const payload = await res.json() as { results?: Array<Record<string, unknown>> };
    for (const m of payload.results ?? []) {
      yield {
        foreignId: String(m.id ?? ""),
        content: String(m.content ?? ""),
        createdAt: typeof m.created_at === "string" ? m.created_at : undefined,
        tags: Array.isArray(m.tags) ? m.tags.map(String) : undefined,
        source: "${name}",
      };
    }
  },

  async export(memories, opts, ctx): Promise<void> {
    ctx.log.info("starting export", { user: String(opts.userId) });
    for await (const m of memories) {
      await ctx.fetch(\`\${String(opts.baseUrl)}/v1/memories\`, {
        method: "POST",
        headers: {
          Authorization: \`Bearer \${String(opts.apiKey)}\`,
          "content-type": "application/json",
        },
        body: JSON.stringify({
          user: String(opts.userId),
          content: m.content,
          tags: m.tags ?? [],
        }),
      });
    }
  },
};

export default bridge;
`;
}

function apiPackageJsonTemplate(name: string): string {
  const pkg = {
    name: `flair-bridge-${name}`,
    version: "0.1.0",
    type: "module",
    description: `Flair bridge for ${name}`,
    main: "index.js",
    types: "index.d.ts",
    scripts: {
      build: "tsc",
    },
    flair: { kind: "api", version: 1 },
    peerDependencies: {
      "@tpsdev-ai/flair": ">=1.0.0",
    },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

function apiFixtureTemplate(name: string): string {
  return JSON.stringify(
    {
      description: `Mock responses for flair-bridge-${name}. Used by 'flair bridge test ${name}'.`,
      import: {
        "GET /v1/memories?user=example": {
          status: 200,
          body: {
            results: [
              { id: "m-1", content: "First imported memory.", tags: ["example"] },
              { id: "m-2", content: "Second imported memory.", tags: ["example"] },
            ],
          },
        },
      },
      export: {
        "POST /v1/memories": { status: 201, body: { ok: true } },
      },
    },
    null,
    2,
  ) + "\n";
}

export async function scaffold(opts: ScaffoldOptions): Promise<ScaffoldResult> {
  if (!NAME_RE.test(opts.name)) {
    throw new Error(
      `invalid bridge name "${opts.name}" — must match ${NAME_RE} (lowercase, digits, hyphens; start with letter).`,
    );
  }
  const cwd = opts.cwd ?? process.cwd();
  const force = opts.force ?? false;

  const createdFiles: string[] = [];
  const skippedFiles: string[] = [];

  const track = async (path: string, content: string) => {
    const { wrote } = await writeIfAbsent(path, content, force);
    if (wrote) createdFiles.push(path);
    else skippedFiles.push(path);
  };

  if (opts.kind === "file") {
    await track(join(cwd, ".flair-bridge", `${opts.name}.yaml`), fileDescriptorTemplate(opts.name));
    await track(join(cwd, ".flair-bridge", "fixtures", `${opts.name}.fixture.jsonl`), fileFixtureTemplate(opts.name));
  } else {
    const pkgDir = join(cwd, `flair-bridge-${opts.name}`);
    await track(join(pkgDir, "index.ts"), apiIndexTemplate(opts.name));
    await track(join(pkgDir, "package.json"), apiPackageJsonTemplate(opts.name));
    await track(join(pkgDir, "fixtures", `${opts.name}.mock.json`), apiFixtureTemplate(opts.name));
  }

  const summary =
    createdFiles.length === 0
      ? `nothing created — all files already exist. Pass --force to overwrite.`
      : `scaffolded ${opts.kind} bridge "${opts.name}". Next: edit the descriptor, then run \`flair bridge test ${opts.name}\`.`;

  return { createdFiles, skippedFiles, summary };
}
