import { Resource, databases, server } from "harper";
import { createHash, randomBytes } from "node:crypto";
import nacl from "tweetnacl";
import { allowAdmin } from "./agent-auth.js";
import {
  canonicalize,
  signBody,
  verifyBodySignature,
  signBodyFresh,
  verifyBodySignatureFresh,
  generateNonce,
} from "./federation-crypto.js";
import { reconcileState } from "./relay-lib.js";
import {
  decideInstanceAnswer,
  INSTANCE_ROW_PRUNE_REMEDY,
  multipleInstanceRowsMessage,
  type InstanceIdentityRow,
} from "../src/lib/instance-identity-row.js";
import { readAllInstanceRows } from "./instance-identity-rows.js";
import { findOrCreateInstance } from "./instance-create-lock.js";
import { withDetachedTxnAsync } from "./table-helpers.js";
import { isSkillWrite } from "./skill-write.js";
import { noteWriteStamp } from "./embedding-space-guard.js";
import { initFederationCleanup } from "./federation-cleanup.js";
import { createPersistentNonceStore, initNonceStoreCleanup } from "./federation-nonce-store.js";
import {
  classifyRecord,
  reconstructRecordVerifyBody,
  checkPrincipalEntitlement,
  type FederationSyncTable,
} from "./federation-classify.js";
export {
  classifyRecord,
  reconstructRecordVerifyBody,
  checkPrincipalEntitlement,
  recordSignatureVersion,
  PRINCIPAL_OWNING_TABLES,
  FEDERATION_TABLE_POLICY,
  FEDERATION_SYNC_TABLES,
} from "./federation-classify.js";
export type { SkipReason, ClassifyResult, FederationSyncTable } from "./federation-classify.js";

// Module-level nonce store for federation anti-replay.
// Shared across FederationPair + FederationSync — nonces are globally unique
// (generated by signBodyFresh per request with 128-bit random nonces).
//
// Backed by the `Nonce` table (federation-edge-hardening slice 4) so a
// process restart doesn't wipe recently-seen nonces within the ±30s
// freshness window — see federation-nonce-store.ts for the full design.
// The NonceStore interface (has/set/evict) stays synchronous, so this swap
// requires NO change to verifyBodySignatureFresh or its 2 call sites below.
const federationNonceStore = createPersistentNonceStore();

// Re-export for consumers that import from Federation.ts
export { canonicalize, signBody, verifyBodySignature, signBodyFresh, verifyBodySignatureFresh, generateNonce };

/**
 * Federation resource — hub-and-spoke sync for Flair instances.
 *
 * Implements:
 * - Instance identity management
 * - Peer pairing (one-shot HTTP handshake)
 * - Sync frame protocol (push/pull over WebSocket)
 * - Conflict resolution (field-level LWW with Lamport clocks)
 * - Peer public key propagation (hub broadcasts PeerAnnouncement frames)
 *
 * Per FLAIR-FEDERATION spec §§ 1-7.
 */

// ─── Sync frame types ────────────────────────────────────────────────────────

interface SyncFrame {
  type: "sync" | "ack" | "peer-announce" | "heartbeat";
  instanceId: string;
  timestamp: string;
  lamportClock: number;
  records?: SyncRecord[];
  peers?: PeerAnnouncement[];
}

interface SyncRecord {
  table: string;             // "Memory" | "Soul" | "Relationship" | "Agent"
  id: string;
  data: Record<string, any>;
  updatedAt: string;         // ISO timestamp — LWW tiebreaker
  originatorInstanceId: string;
  signature?: string;        // Ed25519 signature for agent-originated records
  principalId?: string;      // who authored this record (signed at v:2)
  v?: number;                // signature-body version; absent on today's wire
}

interface PeerAnnouncement {
  instanceId: string;
  publicKey: string;
  role: string;
  endpoint?: string;
}

// ─── Per-record signature enforcement mode (federation-edge-hardening slice 3b) ──

/**
 * Whether FederationSync.post requires EVERY record to carry a valid
 * per-record signature (§3a), skipping unsigned ones (`missing_signature`),
 * vs. the default "verify-if-present" mode where an unsigned record still
 * merges (relying on the batch-level signature already verified above it).
 *
 * Default OFF (verify-if-present) — pre-3a spokes don't sign individual
 * records yet, and their batch is already authenticated. Turning this ON
 * is an OPERATOR decision, never auto-flipped by this code: flip it only
 * once every paired peer has been confirmed sending per-record signatures
 * (e.g. by checking SyncLog for unsigned records / peer versions). Flipping
 * it before every peer has upgraded silently starts dropping that peer's
 * records instead of merging them.
 */
function requireRecordSignatures(): boolean {
  return (process.env.FLAIR_FEDERATION_REQUIRE_RECORD_SIGNATURES ?? "").toLowerCase() === "true";
}

/**
 * Phase 3 of flair#1416 — skip leftover v:1 records on principal-owning
 * tables that lack principalId. Default OFF. Flip only once every paired
 * peer is emitting v:2 (check SyncLog for unsigned / v:1 Memory). Same
 * operator-decision pattern as requireRecordSignatures() — never
 * auto-flipped. v:2 Memory is already mandatory-principal regardless of
 * this flag (see checkPrincipalEntitlement).
 */
function requireRecordPrincipal(): boolean {
  return (process.env.FLAIR_FEDERATION_REQUIRE_RECORD_PRINCIPAL ?? "").toLowerCase() === "true";
}

// ─── Conflict resolution ─────────────────────────────────────────────────────

/**
 * Field-level Last-Write-Wins merge.
 * For each field, the value with the later `updatedAt` wins.
 * Records with no local counterpart are accepted directly.
 */
function mergeRecord(local: Record<string, any> | null, remote: SyncRecord): Record<string, any> {
  if (!local) return remote.data;

  const merged = { ...local };
  const localUpdated = local.updatedAt ?? "";
  const remoteUpdated = remote.updatedAt ?? "";

  // Simple LWW at record level for 1.0
  // Field-level LWW is the spec target but record-level is sufficient
  // for the initial implementation and avoids per-field clock tracking.
  if (remoteUpdated > localUpdated) {
    Object.assign(merged, remote.data);
    merged.updatedAt = remoteUpdated;
  }

  return merged;
}

/**
 * embedding-space-guard slice 1 (the raw-writer-coverage hole K&S found in
 * review #1554): the sync-in merge persists Memory rows via the RAW table
 * handle, bypassing Memory.post()/put(). An LWW remote-win copies the REMOTE
 * `embeddingModel` into `mergedData`, so a memory synced from a spoke on a
 * different engine/model lands a FOREIGN-space vector. Without tripping the
 * vector-space guard's latch, the next recall's O(1) "uniform" consult would
 * cosine that foreign vector = mixed-space garbage — exactly the failure the
 * guard exists to kill. Trip the latch here.
 *
 * `noteWriteStamp` no-ops for a current/bare stamp (a self-originated or
 * same-space sync) and for a non-Memory table (no `embeddingModel`), so only a
 * genuinely foreign Memory sync trips it. Kept as a note-ONLY helper — the raw
 * `table.put(mergedData)` stays INLINE at the call site so the raw-writer
 * coverage gates (authority-field-guard.test.ts / memory-embedding-writer-
 * coverage.test.ts) still enumerate the Memory writer — while the trip decision
 * itself is unit-testable without standing up the full signed sync-in path (see
 * test/unit-isolated/embedding-space-guard-federation.test.ts).
 */
export function noteFederationMergedMemory(
  recordTable: string,
  mergedData: { embeddingModel?: unknown },
): void {
  if (recordTable === "Memory") {
    noteWriteStamp(mergedData.embeddingModel as string | null | undefined);
  }
}

// ─── Instance identity ───────────────────────────────────────────────────────

/**
 * Every `flair.Instance` row on this instance, or a THROWN error — the ONE
 * strict reader (resources/instance-identity-rows.ts), re-exported here so
 * existing consumers keep importing it from the Federation resource.
 *
 * The readers used to take the first row `search()` yielded. `search()` order is
 * not a fact about an identity: on a table with two rows one reader reported one
 * identity and a pairing peer was handed the other, and which was which depended
 * on the table's internal ordering (flair#1883 round 3).
 *
 * A read that FAILS must not look like a table with no rows: the callers answer
 * 5xx and write nothing, because only a SUCCESSFUL read of zero rows may mint an
 * identity.
 *
 * And neither must a row the reader cannot NAME (flair#1883 round 4): an entry
 * without a usable id used to be skipped here, so a table serving one bad entry
 * (or a good one beside it) read as "the rows I could name" — possibly zero — and
 * the GET's create branch could mint a second identity from a read that never
 * saw the table. `readableInstanceRows` throws instead, which the callers map to
 * 5xx and no write.
 */
export { readAllInstanceRows };

/**
 * GET /FederationInstance — return this instance's identity.
 *
 * The admin UI and CLI tooling read it. Peers do NOT read it while pairing: a
 * spoke is handed this instance's identity in the `POST /FederationPair`
 * response, which FederationPair.post() builds server-side by reading the
 * Instance table directly. (The pair CLI must not GET this path to fill a missing
 * pair publicKey either — flair#822: allowRead is allowAdmin, and get() creates an
 * identity when it finds none, which would invent a hub row; #839.)
 *
 * allowRead()=allowAdmin (defense-in-depth, authorizeLocal-escalation-class
 * follow-up to #601/#604/#609/#612 — flair#614's backstop found this one had
 * NO allow* at all, so Harper's own default — `user?.role.permission.
 * super_user`, satisfiable only by a genuine admin OR authorizeLocal's forged
 * loopback super_user — was silently standing in).
 *
 * With SEVERAL rows there is no single identity to report, so this answers 409
 * naming every row and the prune. It never reports the row the search happened
 * to yield first (flair#1883 round 3).
 */
export class FederationInstance extends Resource {
  async allowRead(): Promise<boolean> {
    return allowAdmin((this as any).getContext?.());
  }

  async get() {
    // Find or create instance identity.
    //
    // A read that did not happen is an ERROR, never "no row" (flair#1883 round 2).
    // This used to log and fall through to the create branch: on a persistent
    // storage or permission failure the GET then MINTED A SECOND identity row on
    // every call, and which identity this instance reported depended on which row
    // `search()` yielded first. Only a SUCCESSFUL read that returns zero rows may
    // create.
    // Every row, not the first one (flair#1883 round 3): with several rows the
    // first is a coin toss, and reporting one identity here while a peer is
    // handed another is how the two writers disagreed in the first place.
    let rows: InstanceIdentityRow[] | null = null;
    let readError: any = null;
    try {
      rows = await readAllInstanceRows();
    } catch (err: any) {
      readError = err;
    }

    if (readError) {
      // 5xx: the caller retries, and a retry that finally reads is the only thing
      // that creates. flair#1233's warn stays — the error class belongs in the
      // server log — but it is no longer a licence to write.
      console.error(
        "[federation] GET /FederationInstance could not read the Instance table — answering 503 and creating NOTHING. " +
          "A read error is not first boot; minting an identity here would add a second row to an instance that already has one. " +
          `${readError?.constructor?.name ?? "Error"}: ${readError?.message ?? readError}`,
      );
      return new Response(
        JSON.stringify({
          error: "instance_identity_unreadable",
          detail: "The Instance table could not be read, so this instance's identity is unknown. Nothing was created.",
        }),
        { status: 503, headers: { "content-type": "application/json" } },
      );
    }

    const decision = decideInstanceAnswer(rows);

    if (decision.kind === "refuse-multiple") {
      // 409: several rows means there is no canonical identity, and reporting
      // one of them would be exactly the coin toss #1883 exists to end — a peer
      // could go on to pin it. Nothing is created and nothing is deleted; the
      // operator resolves the table with the prune this names.
      console.error(
        `[federation] GET /FederationInstance found ${decision.rows.length} Instance rows — answering 409 and creating NOTHING. ` +
          "Which row this instance reports must not depend on which row the search yields first.",
      );
      return new Response(
        JSON.stringify({
          error: "multiple_instance_rows",
          detail: multipleInstanceRowsMessage(decision.rows, "GET /FederationInstance"),
          rows: decision.rows,
        }),
        { status: 409, headers: { "content-type": "application/json" } },
      );
    }

    let instance: any = decision.kind === "answer" ? decision.row : null;

    // Runtime-only signal (flair#1233): whether this instance's private key
    // seed is present in the keystore, i.e. whether it can SIGN (pair/sync).
    // Deliberately NOT persisted — the Instance.status enum is
    // schema-constrained and this is transient machine state; recomputed on
    // every GET.
    let signingKeyAvailable = false;

    if (decision.kind === "none") {
      // First boot: the read OUTSIDE the lock found no row. The create runs in the
      // filesystem bakery critical section (flair#1897) — shared by EVERY HTTP
      // worker of this process AND every process on this Flair home: a read taken
      // UNDER the lock, the mint, the put, the keystore seed and a confirming
      // re-read — so two concurrent first-boot GETs mint ONE row and both are
      // answered with it. A GET that found a row above never reaches here, so
      // reads stay concurrent.
      const outcome = await findOrCreateInstance({
        // Detach the request's transaction for EVERY read inside the lock: the
        // outer read above opened the request's transaction BEFORE this create, so
        // reusing it here would read the pre-create snapshot and mint a second row
        // even serialised (the table-helpers.ts class). A fresh transaction sees
        // the row the prior lock holder committed.
        readAll: () => withDetachedTxnAsync((this as any).getContext?.(), () => readAllInstanceRows()),
        // Commit the WRITE before the lock releases: both the row put and the
        // keystore seed run in a DETACHED transaction, so Harper builds a fresh
        // ImmediateTransaction that commits on its own rather than at the end of
        // the request (the lock cannot serialise a write that commits after the
        // method returns — the earlier BLOCKED finding, flair#1897 slice 1).
        put: (row) => withDetachedTxnAsync((this as any).getContext?.(), () => (databases as any).flair.Instance.put(row)),
        setSeed: (createdId, seed) =>
          withDetachedTxnAsync((this as any).getContext?.(), async () => {
            const { keystore } = await import("../src/keystore.js");
            keystore.setPrivateKeySeed(createdId, seed);
          }),
        seedPresent: async (rowId) => {
          try {
            const { keystore } = await import("../src/keystore.js");
            return keystore.getPrivateKeySeed(rowId) !== null;
          } catch {
            return false;
          }
        },
        mint: () => {
          const kp = nacl.sign.keyPair();
          return {
            id: `flair_${randomBytes(4).toString("hex")}`,
            publicKey: Buffer.from(kp.publicKey).toString("base64url"),
            secretKey: kp.secretKey,
          };
        },
      });

      if (outcome.kind === "refuse-multiple") {
        if (outcome.putCommitted) {
          // This request's OWN detached put committed a row AND the table holds >1.
          console.error(
            `[federation] GET /FederationInstance: this request committed row ${outcome.mintedId}; the table now holds ` +
              `${outcome.rows.length} rows — hand to ${INSTANCE_ROW_PRUNE_REMEDY}.`,
          );
          return new Response(
            JSON.stringify({
              error: "multiple_instance_rows",
              detail: multipleInstanceRowsMessage(outcome.rows, "GET /FederationInstance"),
              rows: outcome.rows,
            }),
            { status: 409, headers: { "content-type": "application/json" } },
          );
        }
        // Pre-put (the read before or the first in-lock read) — nothing created.
        console.error(
          `[federation] GET /FederationInstance found ${outcome.rows.length} Instance rows under the create lock — answering 409 and creating NOTHING.`,
        );
        return new Response(
          JSON.stringify({
            error: "multiple_instance_rows",
            detail: multipleInstanceRowsMessage(outcome.rows, "GET /FederationInstance"),
            rows: outcome.rows,
          }),
          { status: 409, headers: { "content-type": "application/json" } },
        );
      }
      if (outcome.kind === "refuse-unobservable") {
        console.error(
          `[federation] GET /FederationInstance: minted ${outcome.mintedId} but the confirming re-read saw NO row — ` +
            `the detached write was not observable. Refusing (no retry).`,
        );
        return new Response(
          JSON.stringify({
            error: "instance_identity_unobservable",
            detail:
              `This instance minted ${outcome.mintedId} but could not read it back — the write did not commit where expected. ` +
              `Nothing is answered. Retry; if it persists, inspect the flair.Instance table.`,
          }),
          { status: 503, headers: { "content-type": "application/json" } },
        );
      }
      if (outcome.kind === "refuse-lock") {
        console.error(`[federation] GET /FederationInstance: ${outcome.detail}`);
        return new Response(
          JSON.stringify({ error: "instance_create_lock_unavailable", detail: outcome.detail }),
          { status: 503, headers: { "content-type": "application/json" } },
        );
      }
      if (outcome.warning) console.error(`[federation] ${outcome.warning}`);
      instance = outcome.row;
      signingKeyAvailable = outcome.seeded;
    } else {
      // Existing identity: report whether its signing key is present and
      // decryptable. getPrivateKeySeed is a read-only probe that returns null
      // (never throws) when the key file is missing or unreadable.
      try {
        const { keystore } = await import("../src/keystore.js");
        signingKeyAvailable = keystore.getPrivateKeySeed(instance.id) !== null;
      } catch {
        signingKeyAvailable = false;
      }
    }

    return {
      id: instance.id,
      publicKey: instance.publicKey,
      role: instance.role,
      status: instance.status,
      // Runtime-only — see above; never persisted.
      signingKeyAvailable,
    };
  }
}

// ─── Peer management ─────────────────────────────────────────────────────────

/**
 * POST /FederationPair — one-shot pairing handshake.
 * A spoke sends its instance identity; the hub records it as a peer.
 * Requires a one-time pairing token generated by `flair federation token`.
 */
export class FederationPair extends Resource {
  // Pairing is a public endpoint by design — spokes have no Harper credentials
  // on the hub yet. The handler self-validates via PairingToken + Ed25519
  // body-signature. Bypassing Harper's role gate is required because Harper's
  // auth layer (security/auth.js) claims any "Bearer X" header for itself,
  // so we route the token through the body instead.
  allowCreate(_user: any, _record: any, _context: any) {
    return true;
  }

  async post(data: any) {
    const { instanceId, publicKey, role, endpoint, signature, pairingToken } = data || {};

    if (!instanceId || !publicKey) {
      return new Response(JSON.stringify({ error: "instanceId and publicKey required" }), {
        status: 400, headers: { "content-type": "application/json" },
      });
    }

    // Verify request signature against the public key (proves key ownership).
    // Uses fresh verification with anti-replay — even though pair has implicit
    // replay protection via single-use pairingToken, explicit anti-replay is
    // defense-in-depth and keeps signature semantics consistent across endpoints.
    if (!signature) {
      return new Response(JSON.stringify({ error: "signature required — request must be signed" }), {
        status: 401, headers: { "content-type": "application/json" },
      });
    }
    const verifyResult = verifyBodySignatureFresh(data, publicKey, {
      windowMs: 30_000,
      nonceStore: federationNonceStore,
    });
    if (!verifyResult.ok) {
      return new Response(JSON.stringify({ error: `invalid signature — ${verifyResult.reason}` }), {
        status: 401, headers: { "content-type": "application/json" },
      });
    }

    // ── The identity this response hands the peer, decided BEFORE the pairing
    // token is consumed, BEFORE the peer is read and before ANY peer is written
    // (flair#1883 round 3). ──────────────────────────────────────────────────
    //
    // NOT "before anything": the signature check above has already run and
    // RECORDED ITS NONCE (verifyBodySignatureFresh → NonceStore.set(), see
    // federation-nonce-store.ts). That is deliberate anti-replay state, not a
    // pairing effect — but it is written, and the refusal is precise about what
    // it precedes.
    //
    // A spoke PINS what it is handed here as its hub peer, so this value is the
    // identity a pairing outcome depends on. It used to be "the first row of an
    // unordered search", read AFTER the pairing token was consumed and the peer
    // written — so a hub holding two rows could burn a one-time token, record the
    // new peer, and only then answer with whichever row the table yielded first.
    // The read now comes first, and an unreadable table or several rows refuse
    // with the token still unused and NO peer written.
    let identityRows: InstanceIdentityRow[] | null = null;
    try {
      identityRows = await readAllInstanceRows();
    } catch (err: any) {
      console.error(
        "[federation] POST /FederationPair could not read the Instance table — answering 503, consuming NO token and writing NO peer. " +
          `${err?.constructor?.name ?? "Error"}: ${err?.message ?? err}`,
      );
      return new Response(
        JSON.stringify({
          error: "instance_identity_unreadable",
          detail:
            "The Instance table could not be read, so this hub's identity is unknown. Nothing was paired: the pairing token is unconsumed and no peer was written.",
        }),
        { status: 503, headers: { "content-type": "application/json" } },
      );
    }
    const identity = decideInstanceAnswer(identityRows);

    if (identity.kind === "refuse-multiple") {
      // 409: with several rows there is no identity this hub can hand a peer
      // without picking one, and the peer would pin the pick. Refuse before the
      // token is consumed and before any Peer row is written.
      //
      // This route is PUBLIC, and this refusal runs before the pairing token or
      // a re-pairing peer's key is checked: any caller with a self-signed body
      // reaches it. So the answer names no row. Each row's id, role and
      // createdAt go to this hub's log; the caller learns only what it can act
      // on: pairing is blocked on the hub side, and the hub's operator resolves
      // it with the prune, which needs admin credentials.
      console.error(
        `[federation] POST /FederationPair answering 409, consuming NO token and writing NO peer. ` +
          multipleInstanceRowsMessage(identity.rows, "POST /FederationPair"),
      );
      return new Response(
        JSON.stringify({
          error: "multiple_instance_rows",
          detail:
            "This hub has more than one Instance row, so it has no single identity to hand a peer. Nothing was paired: " +
            "the pairing token is unconsumed and no peer was written. The hub's operator must keep one row and delete the rest with: " +
            INSTANCE_ROW_PRUNE_REMEDY,
        }),
        { status: 409, headers: { "content-type": "application/json" } },
      );
    }

    // Check if already paired (re-pairing doesn't need a token)
    const existing = await (databases as any).flair.Peer.get(instanceId);
    if (existing) {
      // Re-pairing: verify public key matches (prevents impersonation)
      if (existing.publicKey !== publicKey) {
        return new Response(JSON.stringify({
          error: "public key mismatch — peer already paired with different key",
        }), { status: 409, headers: { "content-type": "application/json" } });
      }
      // Update endpoint and status
      await (databases as any).flair.Peer.put({
        ...existing,
        endpoint: endpoint ?? existing.endpoint,
        status: "paired",
        updatedAt: new Date().toISOString(),
      });
    } else {
      // New peer — require a valid pairing token in the request body.
      // The handler self-validates because the endpoint is public at the
      // Harper-auth and middleware layers (Bearer is not usable on Harper —
      // its auth layer claims unknown Bearer values and 401s).
      if (!pairingToken) {
        return new Response(JSON.stringify({
          error: "pairingToken required in body for first-time pair",
        }), { status: 401, headers: { "content-type": "application/json" } });
      }

      // Fetch the token record for consumption
      let tokenRecord: any = null;
      try {
        tokenRecord = await (databases as any).flair.PairingToken.get(pairingToken);
      } catch { /* table may not exist */ }

      if (!tokenRecord || tokenRecord.consumedBy) {
        return new Response(JSON.stringify({ error: "invalid_or_expired_pairing_token" }), {
          status: 401, headers: { "content-type": "application/json" },
        });
      }
      if (tokenRecord.expiresAt && new Date(tokenRecord.expiresAt) < new Date()) {
        return new Response(JSON.stringify({ error: "invalid_or_expired_pairing_token" }), {
          status: 401, headers: { "content-type": "application/json" },
        });
      }

      // PR-4: bind authenticated bootstrap user to specific pairing token
      const ctx = (this as any).getContext?.() ?? {};
      const authedUser = ctx.request?.tpsAgent;
      const isAdmin = ctx.request?.tpsAgentIsAdmin === true;
      if (!isAdmin && authedUser) {
        const expectedBootstrap = `pair-bootstrap-${pairingToken.slice(0, 8)}`;
        if (authedUser !== expectedBootstrap) {
          return new Response(JSON.stringify({
            error: "bootstrap_user_token_mismatch",
          }), { status: 401, headers: { "content-type": "application/json" } });
        }
      }

      // Consume the token
      await (databases as any).flair.PairingToken.put({
        ...tokenRecord,
        consumedBy: instanceId,
        consumedAt: new Date().toISOString(),
      });

      await (databases as any).flair.Peer.put({
        id: instanceId,
        publicKey,
        role: role ?? "spoke",
        endpoint: endpoint ?? null,
        status: "paired",
        relayOnly: false,
        pairedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });

      // Drop the bootstrap user that was created alongside this pairing token.
      // Failure here is non-fatal: the cleanup sweep (PR-5) will catch stragglers.
      try {
        const bootstrapUsername = `pair-bootstrap-${pairingToken.slice(0, 8)}`;
        await server.operation(
          { operation: "drop_user", username: bootstrapUsername },
          ctx,
          false,
        );
      } catch (err: any) {
        console.warn(`[federation] drop_user failed: ${err?.message} — cleanup sweep will retry`);
      }
    }

    // Return our own identity for the peer to record — `{ id, publicKey, role }`,
    // decided BEFORE the token was consumed (above; flair#1883 round 3). An
    // `instance` of `null` means a SUCCESSFUL read found no FederationInstance:
    // that is #839, not a pair-response-shape bug. The spoke must ERROR, never
    // store publicKey:"" (flair#822).
    return {
      paired: true,
      instance: identity.kind === "answer" ? {
        id: identity.row.id,
        publicKey: identity.row.publicKey,
        role: identity.row.role,
      } : null,
    };
  }
}

// ─── Sync endpoint ───────────────────────────────────────────────────────────

/**
 * POST /FederationSync — push sync records from a peer.
 * In 1.0, this is a simple HTTP push (not WebSocket).
 * The calling peer sends a batch of SyncRecords; we merge them.
 */
export class FederationSync extends Resource {
  // Public endpoint by design: spokes have no Harper credentials. Body signature
  // (with timestamp + nonce, via verifyBodySignatureFresh) is the auth boundary.
  // Same pattern as FederationPair.
  allowCreate(_user: any, _record: any, _context: any) {
    return true;
  }

  async post(data: any) {
    const { instanceId, records, lamportClock, signature } = data || {};

    if (!instanceId || !Array.isArray(records)) {
      return new Response(JSON.stringify({ error: "instanceId and records[] required" }), {
        status: 400, headers: { "content-type": "application/json" },
      });
    }

    // Verify peer is known
    const peer = await (databases as any).flair.Peer.get(instanceId);
    if (!peer || peer.status === "revoked") {
      return new Response(JSON.stringify({ error: "unknown or revoked peer" }), {
        status: 403, headers: { "content-type": "application/json" },
      });
    }

    // Verify request signature against peer's pinned public key.
    // Fresh verification with anti-replay — prevents captured signatures from
    // being replayed across the timestamp window.
    if (!signature) {
      return new Response(JSON.stringify({ error: "signature required — sync requests must be signed" }), {
        status: 401, headers: { "content-type": "application/json" },
      });
    }
    const verifyResult = verifyBodySignatureFresh(data, peer.publicKey, {
      windowMs: 30_000,
      nonceStore: federationNonceStore,
    });
    if (!verifyResult.ok) {
      return new Response(JSON.stringify({ error: `invalid signature — ${verifyResult.reason}` }), {
        status: 401, headers: { "content-type": "application/json" },
      });
    }

    const startTime = Date.now();
    let merged = 0;
    let skipped = 0;
    const skippedReasons: Record<string, number> = {};
    const mergeErrors: string[] = [];

    function recordSkip(reason: string) {
      skipped++;
      skippedReasons[reason] = (skippedReasons[reason] ?? 0) + 1;
    }

    // Table name → Harper database table mapping.
    // Typed against FEDERATION_TABLE_POLICY so adding a federated table
    // without deciding principalOwning is a type error, not a silent
    // default (flair#1416 — refuse by whitelist, never by field presence).
    const tableMap: Record<FederationSyncTable, any> = {
      Memory: (databases as any).flair.Memory,
      Soul: (databases as any).flair.Soul,
      Agent: (databases as any).flair.Agent,
      Relationship: (databases as any).flair.Relationship,
      // Flair Relay (flair#1521). Registered so the policy + owner-field land now
      // (the design's ship-order). No spoke pushes Message records in S1 — this is the
      // RECEIVE side only; the absorbing-state guard below keeps an incoming
      // Message merge from ever regressing a locally-consumed row (§12 P0-3).
      //
      // S2 COMMENT-PIN (Kern P1-4, flair#1521): the receive-only carve-out means
      // an incoming Message record is verified only at the RECORD level (batch
      // signature, per-record originator signature, principalId == `from`) — the
      // ENVELOPE's own signature + contentHash (relay-lib.ts verifyMessageSignature)
      // NEVER runs on this merge path. Correct for S1 (nothing pushes Message).
      // But the FIRST hub that pushes Message would merge unverified envelope
      // content silently: S2 MUST add envelope verification here (or an explicit
      // trust delegation to the originator's send-time check) alongside adding
      // Message to the push list — do not inherit this as a silent gap.
      Message: (databases as any).flair.Message,
    };
    const knownTables = new Set(Object.keys(tableMap));

    for (const record of records as SyncRecord[]) {
      try {
        const table = (record.table in tableMap)
          ? tableMap[record.table as FederationSyncTable]
          : undefined;
        const local = table ? await table.get(record.id) : null;

        const decision = classifyRecord(
          record,
          peer.role,
          instanceId,
          local,
          knownTables,
        );

        if (decision.action === "skip") {
          recordSkip(decision.reason);
          continue;
        }

        // ── Per-record signature verification (federation-edge-hardening slice 3b) ──
        // classifyRecord's "merge" verdict above only proves the record is
        // STRUCTURALLY eligible (known table, self-originated OR the sender
        // is a hub, not stale, not a no-op) — that hub bypass trusts the
        // BATCH-level signature (verifyBodySignatureFresh above, verified
        // against the SENDER's pinned key). It does NOT prove the record's
        // *claimed* originator actually produced it — a hub relaying on
        // behalf of many spokes could otherwise forge a record under any
        // originatorInstanceId it likes, and the receiver had no way to
        // tell. This gate closes that hole: verify the record's own
        // signature (§3a, set at push-time by the ORIGINATOR, never by
        // whoever relayed it) against the ORIGINATOR's pinned instance key
        // — never the sender's key.
        //
        // A bad/unverifiable signature skips ONLY this record, never the
        // batch — rejecting the whole batch on one bad record would be a
        // DoS vector (one forged/garbled record could blackhole every other
        // legitimate record riding along in the same POST).
        const originator = decision.originator;
        if (record.signature) {
          const originatorPublicKey = originator === instanceId
            ? peer.publicKey
            : (await (databases as any).flair.Peer.get(originator))?.publicKey;

          if (!originatorPublicKey) {
            recordSkip("unknown_originator_key");
            continue;
          }

          // CONTRACT — reconstruct from the record (v defaults to 1 when
          // absent — v is NOT on the wire today). Must match
          // reconstructRecordVerifyBody / src/cli.ts's signing payload.
          // A hardcoded { v: 1, table, id, data, updatedAt,
          // originatorInstanceId } field set can only ever verify one
          // shape; building from the record is what makes v:2 (principalId
          // in the signed body) verifiable without breaking existing
          // records. See flair#1416.
          const signatureValid = verifyBodySignature(
            reconstructRecordVerifyBody(record, originator),
            originatorPublicKey,
          );
          if (!signatureValid) {
            recordSkip("invalid_signature");
            continue;
          }
        } else if (requireRecordSignatures()) {
          // require-mode: unsigned records are no longer trusted on
          // batch-level auth alone. Default mode (verify-if-present) falls
          // through here and merges — see requireRecordSignatures() above.
          recordSkip("missing_signature");
          continue;
        }

        // ── Per-record principal entitlement (flair#1416 / slice 3a) ──
        // After signature verification, before table.put. Scoped by the
        // explicit PRINCIPAL_OWNING_TABLES set (Memory), never by whether
        // principalId happens to be present — absent Memory principalId
        // is a skip, not an accept. Soul/Agent/Relationship are not in
        // the set and are not consulted. No Agent.get.
        const principalSkip = checkPrincipalEntitlement(record, {
          enforceV1Principal: requireRecordPrincipal(),
        });
        if (principalSkip) {
          recordSkip(principalSkip);
          continue;
        }

        const mergedData = mergeRecord(local, record);

        // ── flair#1542: skills are not federated ──
        // A skill-tagged Memory is a local, gated artifact (SkillScan + forced
        // durability on the write path). Merging a pushed skill-tagged row RAW
        // would land an unscanned, possibly non-persistent skill — bypassing the
        // gate. Skip it: skills are written locally via skill_store, never synced.
        if (record.table === "Memory" && isSkillWrite(mergedData)) {
          recordSkip("skill_not_federated");
          continue;
        }

        // Absorbing-state guard for the Message table (flair#1521 §12 P0-3).
        // Generic newer-wins LWW would let a deadline-sweep `failed` (or any
        // other state) written on a peer overwrite a locally-CONSUMED message,
        // telling the sender "failed" about a message the recipient actually
        // consumed — the exact inversion Relay exists to kill. `consumed` is
        // absorbing: reconcileState pins it regardless of updatedAt. The guard
        // lives HERE, in the raw-put apply path, because sync-in bypasses the
        // Message resource's methods (Federation.ts uses table.put directly).
        if (record.table === "Message") {
          const reconciled = reconcileState(local?.state, mergedData.state);
          mergedData.state = reconciled;
          // P1-3 (flair#1521): reconcile the SATELLITE lifecycle fields too, not
          // just `state`. Generic LWW keeps the incoming (newer) record's
          // failureReason/consumedAt, so a locally-CONSUMED row could end up
          // `consumed` while carrying a remote `failureReason: "deadline"` — the
          // sender-visible "failed" about a message the recipient actually
          // consumed, the exact inversion the absorbing rule exists to kill. A
          // consumed row NEVER has a failureReason; keep the consumed row's own
          // consumedAt (local's when local was the consumer).
          if (reconciled === "consumed") {
            mergedData.failureReason = null;
            mergedData.consumedAt = local?.consumedAt ?? mergedData.consumedAt ?? null;
          }
        }

        mergedData._originatorInstanceId = decision.originator;
        mergedData._syncedFrom = instanceId;
        mergedData._syncedAt = new Date().toISOString();

        await table.put(mergedData);
        // embedding-space-guard slice 1: a federation-merged Memory can carry a
        // FOREIGN embeddingModel (LWW remote-win) — trip the guard's latch so
        // recall/dedup degrade instead of cosining a foreign vector. See
        // noteFederationMergedMemory's doc.
        noteFederationMergedMemory(record.table, mergedData);
        merged++;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        recordSkip("merge_error");
        // Cap the captured-error list so a hostile/buggy peer can't blow up
        // the SyncLog row, but ALWAYS log to console so operators don't lose
        // the per-record signal — the silent-swallow is the bug we're fixing.
        if (mergeErrors.length < 10) {
          mergeErrors.push(`${record.table}/${record.id}: ${msg}`);
        }
        console.warn(
          `[Federation] merge error for ${record.table}/${record.id} from ${instanceId}: ${msg}`,
        );
      }
    }

    // Peer cursor update — distinguish liveness from progress:
    //   lastSyncAt → "we heard from this peer just now" (always update)
    //   lastMergeAt → "data actually flowed in" (only when merged > 0)
    // Conflating them produced the "green dashboard while burning" failure
    // mode — dogfood pass 2026-05-26 surfaced unconditional update masking
    // 100%-skip syncs.
    const nowIso = new Date().toISOString();
    const peerUpdate: Record<string, any> = {
      ...peer,
      lastSyncAt: nowIso,
      lastSyncCursor: lamportClock?.toString() ?? nowIso,
      status: "connected",
      updatedAt: nowIso,
    };
    if (merged > 0) {
      peerUpdate.lastMergeAt = nowIso;
    }
    await (databases as any).flair.Peer.put(peerUpdate);

    // Log sync operation with skip-reason breakdown so the partial state
    // is debuggable instead of a black box.
    try {
      const errorParts: string[] = [];
      if (Object.keys(skippedReasons).length > 0) {
        errorParts.push(
          "skipped: " +
            Object.entries(skippedReasons)
              .map(([reason, n]) => `${n} ${reason}`)
              .join(", "),
        );
      }
      if (mergeErrors.length > 0) {
        errorParts.push("merge_errors: " + mergeErrors.join("; "));
      }
      const errorSummary = errorParts.length > 0 ? errorParts.join(" | ") : undefined;
      const status = mergeErrors.length > 0
        ? "partial"
        : skipped > 0 ? "partial" : "success";

      await (databases as any).flair.SyncLog.put({
        id: `sync_${Date.now()}_${randomBytes(4).toString("hex")}`,
        peerId: instanceId,
        direction: "pull",
        recordCount: merged,
        skippedCount: skipped,
        skippedReasons: JSON.stringify(skippedReasons),
        status,
        error: errorSummary,
        durationMs: Date.now() - startTime,
        createdAt: nowIso,
      });
    } catch { /* non-fatal */ }

    return {
      merged,
      skipped,
      skippedReasons,
      total: records.length,
      durationMs: Date.now() - startTime,
    };
  }
}

/**
 * GET /FederationPeers — list known peers (admin view).
 *
 * allowRead()=allowAdmin (defense-in-depth, authorizeLocal-escalation-class
 * follow-up to #601/#604/#609/#612 — flair#614's backstop found this one had
 * NO allow* at all). The docstring already called this "(admin view)" — this
 * closes the gap between the documented/intended access model and what was
 * actually enforced (nothing).
 */
export class FederationPeers extends Resource {
  async allowRead(): Promise<boolean> {
    return allowAdmin((this as any).getContext?.());
  }

  async get() {
    const peers: any[] = [];
    try {
      for await (const p of (databases as any).flair.Peer.search()) {
        peers.push({
          id: p.id,
          role: p.role,
          status: p.status,
          endpoint: p.endpoint,
          lastSyncAt: p.lastSyncAt,
          lastMergeAt: p.lastMergeAt,
          relayOnly: p.relayOnly,
          pairedAt: p.pairedAt,
        });
      }
    } catch {}
    return { peers };
  }
}

// ── Module initialisation ────────────────────────────────────────────────────
// Deferred: the cleanup sweep (PR-5) starts after the module graph resolves.
// In unit test environments (no Harper runtime), setTimeout never fires
// synchronously and import is safe. In the live Harper process, the sweep
// will start on the next event loop tick and runs only on hub instances.
if (typeof setTimeout !== "undefined") {
  setTimeout(() => {
    initFederationCleanup().catch((err: any) => {
      // Swallow — in test/resource-env the Harper databases may not be bound.
      // In production, initFederationCleanup handles its own error paths.
    });

    // Nonce store hydration (slice 4) — load nonces persisted by a previous
    // process (if any) before this instance starts guarding live traffic.
    // Runs on the same deferred tick as the cleanup sweep above; there is a
    // narrow window between process start and hydration completing during
    // which a pre-restart nonce isn't yet visible — an accepted tradeoff
    // consistent with this file's existing deferred-init pattern (see the
    // cleanup sweep comment above).
    federationNonceStore.hydrate().catch((err: any) => {
      // Swallow — in test/resource-env the Harper databases may not be bound.
    });

    // Nonce table eviction sweep — runs on every instance (both hub and
    // spoke can be the receiving/verifying side of a signed federation
    // request), unlike PairingToken cleanup which is hub-only.
    initNonceStoreCleanup().catch((err: any) => {
      // Swallow — in test/resource-env the Harper databases may not be bound.
    });
  }, 0);
}
