import { Resource, databases } from "@harperfast/harper";
import { createHash, randomBytes } from "node:crypto";
import nacl from "tweetnacl";
import { canonicalize, signBody, verifyBodySignature } from "./federation-crypto.js";

// Re-export for consumers that import from Federation.ts
export { canonicalize, signBody, verifyBodySignature };

/**
 * Federation resource — hub-and-spoke sync for Flair instances.
 *
 * Implements:
 * - Instance identity management
 * - Peer pairing (one-shot HTTP handshake)
 * - Sync frame protocol (push/pull over WebSocket)
 * - Conflict resolution (field-level LWW with Lamport clocks)
 * - Peer public key propagation (hub broadcasts PeerAnnouncement frames)
 *
 * Per FLAIR-FEDERATION spec §§ 1-7.
 */

// ─── Sync frame types ────────────────────────────────────────────────────────

interface SyncFrame {
  type: "sync" | "ack" | "peer-announce" | "heartbeat";
  instanceId: string;
  timestamp: string;
  lamportClock: number;
  records?: SyncRecord[];
  peers?: PeerAnnouncement[];
}

interface SyncRecord {
  table: string;             // "Memory" | "Soul" | "Relationship" | "Agent"
  id: string;
  data: Record<string, any>;
  updatedAt: string;         // ISO timestamp — LWW tiebreaker
  originatorInstanceId: string;
  signature?: string;        // Ed25519 signature for agent-originated records
  principalId?: string;      // who authored this record
}

interface PeerAnnouncement {
  instanceId: string;
  publicKey: string;
  role: string;
  endpoint?: string;
}

// ─── Conflict resolution ─────────────────────────────────────────────────────

/**
 * Field-level Last-Write-Wins merge.
 * For each field, the value with the later `updatedAt` wins.
 * Records with no local counterpart are accepted directly.
 */
function mergeRecord(local: Record<string, any> | null, remote: SyncRecord): Record<string, any> {
  if (!local) return remote.data;

  const merged = { ...local };
  const localUpdated = local.updatedAt ?? "";
  const remoteUpdated = remote.updatedAt ?? "";

  // Simple LWW at record level for 1.0
  // Field-level LWW is the spec target but record-level is sufficient
  // for the initial implementation and avoids per-field clock tracking.
  if (remoteUpdated > localUpdated) {
    Object.assign(merged, remote.data);
    merged.updatedAt = remoteUpdated;
  }

  return merged;
}

// ─── Instance identity ───────────────────────────────────────────────────────

/**
 * GET /FederationInstance — return this instance's identity.
 * Used by peers during pairing and by the admin UI.
 */
export class FederationInstance extends Resource {
  async get() {
    // Find or create instance identity
    let instance: any = null;
    try {
      for await (const i of (databases as any).flair.Instance.search()) {
        instance = i;
        break;
      }
    } catch { /* table may not exist */ }

    if (!instance) {
      // First boot — generate instance identity
      const kp = nacl.sign.keyPair();
      const id = `flair_${randomBytes(4).toString("hex")}`;
      const publicKey = Buffer.from(kp.publicKey).toString("base64url");

      instance = {
        id,
        publicKey,
        role: "spoke", // default; hub is set during `flair init --remote`
        status: "active",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      await (databases as any).flair.Instance.put(instance);

      // Store private key seed in encrypted keystore (not in DB)
      try {
        const { keystore } = await import("../src/keystore.js");
        const seed = kp.secretKey.slice(0, 32);
        keystore.setPrivateKeySeed(id, seed);
      } catch (err) {
        // Fail closed — never store plaintext keys in the database
        console.error("[federation] FATAL: Could not store key seed in keystore. Federation identity not created.", err);
        throw new Error("Keystore unavailable — cannot create federation identity without secure key storage");
      }
    }

    return {
      id: instance.id,
      publicKey: instance.publicKey,
      role: instance.role,
      status: instance.status,
    };
  }
}

// ─── Peer management ─────────────────────────────────────────────────────────

/**
 * POST /FederationPair — one-shot pairing handshake.
 * A spoke sends its instance identity; the hub records it as a peer.
 * Requires a one-time pairing token generated by `flair federation token`.
 */
export class FederationPair extends Resource {
  // Pairing is a public endpoint by design — spokes have no Harper credentials
  // on the hub yet. The handler self-validates via PairingToken + Ed25519
  // body-signature. Bypassing Harper's role gate is required because Harper's
  // auth layer (security/auth.js) claims any "Bearer X" header for itself,
  // so we route the token through the body instead.
  allowCreate(_user: any, _record: any, _context: any) {
    return true;
  }

  async post(data: any) {
    const { instanceId, publicKey, role, endpoint, signature, pairingToken } = data || {};

    if (!instanceId || !publicKey) {
      return new Response(JSON.stringify({ error: "instanceId and publicKey required" }), {
        status: 400, headers: { "content-type": "application/json" },
      });
    }

    // Verify signature — the pairing body must be signed with the private key
    // corresponding to the publicKey in the body (proves key ownership).
    if (!signature) {
      return new Response(JSON.stringify({ error: "signature required — request must be signed" }), {
        status: 401, headers: { "content-type": "application/json" },
      });
    }
    if (!verifyBodySignature(data, publicKey)) {
      return new Response(JSON.stringify({ error: "invalid signature — key ownership proof failed" }), {
        status: 401, headers: { "content-type": "application/json" },
      });
    }

    // Check if already paired (re-pairing doesn't need a token)
    const existing = await (databases as any).flair.Peer.get(instanceId);
    if (existing) {
      // Re-pairing: verify public key matches (prevents impersonation)
      if (existing.publicKey !== publicKey) {
        return new Response(JSON.stringify({
          error: "public key mismatch — peer already paired with different key",
        }), { status: 409, headers: { "content-type": "application/json" } });
      }
      // Update endpoint and status
      await (databases as any).flair.Peer.put({
        ...existing,
        endpoint: endpoint ?? existing.endpoint,
        status: "paired",
        updatedAt: new Date().toISOString(),
      });
    } else {
      // New peer — require a valid pairing token in the request body.
      // The handler self-validates because the endpoint is public at the
      // Harper-auth and middleware layers (Bearer is not usable on Harper —
      // its auth layer claims unknown Bearer values and 401s).
      if (!pairingToken) {
        return new Response(JSON.stringify({
          error: "pairingToken required in body for first-time pair",
        }), { status: 401, headers: { "content-type": "application/json" } });
      }

      // Fetch the token record for consumption
      let tokenRecord: any = null;
      try {
        tokenRecord = await (databases as any).flair.PairingToken.get(pairingToken);
      } catch { /* table may not exist */ }

      if (!tokenRecord || tokenRecord.consumedBy) {
        return new Response(JSON.stringify({ error: "invalid_or_expired_pairing_token" }), {
          status: 401, headers: { "content-type": "application/json" },
        });
      }
      if (tokenRecord.expiresAt && new Date(tokenRecord.expiresAt) < new Date()) {
        return new Response(JSON.stringify({ error: "invalid_or_expired_pairing_token" }), {
          status: 401, headers: { "content-type": "application/json" },
        });
      }

      // Consume the token
      await (databases as any).flair.PairingToken.put({
        ...tokenRecord,
        consumedBy: instanceId,
        consumedAt: new Date().toISOString(),
      });

      await (databases as any).flair.Peer.put({
        id: instanceId,
        publicKey,
        role: role ?? "spoke",
        endpoint: endpoint ?? null,
        status: "paired",
        relayOnly: false,
        pairedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });

      // Drop the bootstrap user that was created alongside this pairing token.
      // Failure here is non-fatal: a cleanup cron (PR-5) will catch stragglers.
      try {
        const bootstrapUsername = `pair-bootstrap-${pairingToken.slice(0, 8)}`;
        const opsPort = process.env.FLAIR_OPS_PORT
          ? Number(process.env.FLAIR_OPS_PORT)
          : (process.env.FLAIR_PORT ? Number(process.env.FLAIR_PORT) - 1 : 19925);
        const opsUrl = `http://127.0.0.1:${opsPort}/`;
        const adminPass = process.env.HDB_ADMIN_PASSWORD ?? process.env.FLAIR_ADMIN_PASSWORD ?? "";
        const auth = `Basic ${Buffer.from(`admin:${adminPass}`).toString("base64")}`;
        const dropRes = await fetch(opsUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json", Authorization: auth },
          body: JSON.stringify({ operation: "drop_user", username: bootstrapUsername }),
          signal: AbortSignal.timeout(10_000),
        });
        if (!dropRes.ok) {
          const detail = await dropRes.text().catch(() => "");
          console.warn(`[federation] drop_user ${bootstrapUsername} failed (${dropRes.status}): ${detail} — cleanup cron will retry`);
        }
      } catch (err: any) {
        console.warn(`[federation] drop_user failed (network): ${err?.message} — cleanup cron will retry`);
      }
    }

    // Return our own identity for the peer to record
    let ourInstance: any = null;
    try {
      for await (const i of (databases as any).flair.Instance.search()) {
        ourInstance = i;
        break;
      }
    } catch {}

    return {
      paired: true,
      instance: ourInstance ? {
        id: ourInstance.id,
        publicKey: ourInstance.publicKey,
        role: ourInstance.role,
      } : null,
    };
  }
}

// ─── Sync endpoint ───────────────────────────────────────────────────────────

/**
 * POST /FederationSync — push sync records from a peer.
 * In 1.0, this is a simple HTTP push (not WebSocket).
 * The calling peer sends a batch of SyncRecords; we merge them.
 */
export class FederationSync extends Resource {
  async post(data: any) {
    const { instanceId, records, lamportClock, signature } = data || {};

    if (!instanceId || !Array.isArray(records)) {
      return new Response(JSON.stringify({ error: "instanceId and records[] required" }), {
        status: 400, headers: { "content-type": "application/json" },
      });
    }

    // Verify peer is known
    const peer = await (databases as any).flair.Peer.get(instanceId);
    if (!peer || peer.status === "revoked") {
      return new Response(JSON.stringify({ error: "unknown or revoked peer" }), {
        status: 403, headers: { "content-type": "application/json" },
      });
    }

    // Verify request signature against peer's pinned public key
    if (!signature) {
      return new Response(JSON.stringify({ error: "signature required — sync requests must be signed" }), {
        status: 401, headers: { "content-type": "application/json" },
      });
    }
    if (!verifyBodySignature(data, peer.publicKey)) {
      return new Response(JSON.stringify({ error: "invalid signature — request not from claimed peer" }), {
        status: 401, headers: { "content-type": "application/json" },
      });
    }

    const startTime = Date.now();
    let merged = 0;
    let skipped = 0;

    // Table name → Harper database table mapping
    const tableMap: Record<string, any> = {
      Memory: (databases as any).flair.Memory,
      Soul: (databases as any).flair.Soul,
      Agent: (databases as any).flair.Agent,
      Relationship: (databases as any).flair.Relationship,
    };

    for (const record of records as SyncRecord[]) {
      const table = tableMap[record.table];
      if (!table) {
        skipped++;
        continue;
      }

      // Originator enforcement: peers can only push records they originated.
      // The hub can relay records from other peers (role === "hub"),
      // but spokes can only push their own records.
      const originator = record.originatorInstanceId ?? instanceId;
      if (originator !== instanceId && peer.role !== "hub") {
        skipped++;
        continue;
      }

      try {
        const local = await table.get(record.id);

        // Timestamp ceiling: reject records with updatedAt more than 5 minutes in the future.
        // Prevents attackers from using far-future timestamps to permanently win LWW.
        const fiveMinFromNow = new Date(Date.now() + 5 * 60 * 1000).toISOString();
        if (record.updatedAt > fiveMinFromNow) {
          skipped++;
          continue;
        }

        const mergedData = mergeRecord(local, record);

        // Preserve originator for provenance
        mergedData._originatorInstanceId = originator;
        mergedData._syncedFrom = instanceId;
        mergedData._syncedAt = new Date().toISOString();

        await table.put(mergedData);
        merged++;
      } catch {
        skipped++;
      }
    }

    // Update peer sync cursor
    await (databases as any).flair.Peer.put({
      ...peer,
      lastSyncAt: new Date().toISOString(),
      lastSyncCursor: lamportClock?.toString() ?? new Date().toISOString(),
      status: "connected",
      updatedAt: new Date().toISOString(),
    });

    // Log sync operation
    try {
      await (databases as any).flair.SyncLog.put({
        id: `sync_${Date.now()}_${randomBytes(4).toString("hex")}`,
        peerId: instanceId,
        direction: "pull",
        recordCount: merged,
        status: skipped > 0 ? "partial" : "success",
        error: skipped > 0 ? `${skipped} records skipped` : undefined,
        durationMs: Date.now() - startTime,
        createdAt: new Date().toISOString(),
      });
    } catch { /* non-fatal */ }

    return {
      merged,
      skipped,
      total: records.length,
      durationMs: Date.now() - startTime,
    };
  }
}

/**
 * GET /FederationPeers — list known peers (admin view).
 */
export class FederationPeers extends Resource {
  async get() {
    const peers: any[] = [];
    try {
      for await (const p of (databases as any).flair.Peer.search()) {
        peers.push({
          id: p.id,
          role: p.role,
          status: p.status,
          endpoint: p.endpoint,
          lastSyncAt: p.lastSyncAt,
          relayOnly: p.relayOnly,
          pairedAt: p.pairedAt,
        });
      }
    } catch {}
    return { peers };
  }
}
